*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to 127.0.0.1:37181 (IPv4)
Extension host agent listening on 37181

[20:18:52] Extension host agent started.
[20:18:52] [127.0.0.1][06855aa6][ManagementConnection] New connection established.
[20:18:52] [127.0.0.1][578c6194][ExtensionHostConnection] New connection established.
[20:18:52] [127.0.0.1][578c6194][ExtensionHostConnection] <2122796> Launched Extension Host Process.
rejected promise not handled within 1 second: Error: Could not find pty on pty host
stack trace: Error: Could not find pty on pty host,    at m._throwIfNoPty (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:5333),    at m.updateTitle (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:1673),    at Object.call (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:13:8361),    at g.onPromise (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4879),    at g.onRawMessage (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4267),    at /home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:3555,    at D.invoke (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at N.deliver (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:2271),    at h.fire (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:1849),    at process.p (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:6:34973),    at process.emit (node:events:390:28),    at emit (node:internal/child_process:917:12),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[20:18:54] [Error: Could not find pty on pty host,    at m._throwIfNoPty (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:5333),    at m.updateTitle (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:1673),    at Object.call (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:13:8361),    at g.onPromise (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4879),    at g.onRawMessage (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4267),    at /home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:3555,    at D.invoke (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at N.deliver (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:2271),    at h.fire (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:1849),    at process.p (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:6:34973),    at process.emit (node:events:390:28),    at emit (node:internal/child_process:917:12),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
[20:20:49] [127.0.0.1][06855aa6][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[20:20:49] [127.0.0.1][578c6194][ExtensionHostConnection] <2122796> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[20:20:49] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[20:21:14] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[20:21:14] Cancelling previous shutdown timeout
[20:21:14] [127.0.0.1][bcf7c839][ManagementConnection] New connection established.
[20:21:14] [127.0.0.1][36948935][ExtensionHostConnection] New connection established.
[20:21:14] [127.0.0.1][36948935][ExtensionHostConnection] <2123298> Launched Extension Host Process.
[20:21:55] [127.0.0.1][bcf7c839][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[20:21:55] [127.0.0.1][36948935][ExtensionHostConnection] <2123298> Extension Host Process exited with code: 0, signal: null.
Cancelling previous shutdown timeout
[20:21:55] Cancelling previous shutdown timeout
Last EH closed, waiting before shutting down
[20:21:55] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[20:22:08] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[20:22:08] Cancelling previous shutdown timeout
[20:22:08] [127.0.0.1][c2c78f18][ManagementConnection] New connection established.
[20:22:08] [127.0.0.1][c89c6c6f][ExtensionHostConnection] New connection established.
[20:22:08] [127.0.0.1][c89c6c6f][ExtensionHostConnection] <2123792> Launched Extension Host Process.
Got delay-shutdown request while in shutdown timeout, delaying
[20:23:44] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[20:23:44] Cancelling previous shutdown timeout
[20:23:44] [127.0.0.1][5703a06a][ManagementConnection] New connection established.
[20:23:44] [127.0.0.1][ab0acc9f][ExtensionHostConnection] New connection established.
[20:23:44] [127.0.0.1][ab0acc9f][ExtensionHostConnection] <2124275> Launched Extension Host Process.
[20:25:35] [127.0.0.1][c2c78f18][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[20:25:35] [127.0.0.1][c89c6c6f][ExtensionHostConnection] <2123792> Extension Host Process exited with code: 0, signal: null.
Cancelling previous shutdown timeout
[20:25:35] Cancelling previous shutdown timeout
[20:25:37] [127.0.0.1][5703a06a][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[20:25:37] [127.0.0.1][ab0acc9f][ExtensionHostConnection] <2124275> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[20:25:37] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[20:27:27] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[20:27:27] Cancelling previous shutdown timeout
[20:27:27] [127.0.0.1][b28bd46f][ManagementConnection] New connection established.
[20:27:27] [127.0.0.1][39f70e30][ExtensionHostConnection] New connection established.
[20:27:27] [127.0.0.1][39f70e30][ExtensionHostConnection] <2125069> Launched Extension Host Process.
rejected promise not handled within 1 second: Error: Could not find pty on pty host
stack trace: Error: Could not find pty on pty host,    at m._throwIfNoPty (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:5333),    at m.updateTitle (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:1673),    at Object.call (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:13:8361),    at g.onPromise (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4879),    at g.onRawMessage (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4267),    at /home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:3555,    at D.invoke (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at N.deliver (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:2271),    at h.fire (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:1849),    at process.p (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:6:34973),    at process.emit (node:events:390:28),    at emit (node:internal/child_process:917:12),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[20:27:28] [Error: Could not find pty on pty host,    at m._throwIfNoPty (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:5333),    at m.updateTitle (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:1673),    at Object.call (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:13:8361),    at g.onPromise (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4879),    at g.onRawMessage (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4267),    at /home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:3555,    at D.invoke (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at N.deliver (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:2271),    at h.fire (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:1849),    at process.p (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:6:34973),    at process.emit (node:events:390:28),    at emit (node:internal/child_process:917:12),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
New EH opened, aborting shutdown
[20:32:27] New EH opened, aborting shutdown
[20:49:10] [127.0.0.1][b28bd46f][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[20:49:10] Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/server/node/server.main.js:143:7914)
    at process.emit (node:events:390:28)
[21:45:21] [127.0.0.1][b28bd46f][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[21:45:21] [127.0.0.1][fe2da216][ExtensionHostConnection] New connection established.
[21:45:21] [127.0.0.1][da37bac1][ManagementConnection] New connection established.
[21:45:21] [127.0.0.1][fe2da216][ExtensionHostConnection] <2558105> Launched Extension Host Process.
[21:46:56] [127.0.0.1][da37bac1][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[21:46:56] [127.0.0.1][fe2da216][ExtensionHostConnection] <2558105> Extension Host Process exited with code: 0, signal: null.
[21:47:27] [127.0.0.1][93687a4a][ManagementConnection] New connection established.
[21:47:27] [127.0.0.1][bafcecf3][ExtensionHostConnection] New connection established.
[21:47:27] [127.0.0.1][bafcecf3][ExtensionHostConnection] <2558525> Launched Extension Host Process.
[21:50:21] [127.0.0.1][b28bd46f][ManagementConnection] The reconnection short grace time of 5m has expired, so the connection will be disposed.
[21:50:21] [127.0.0.1][39f70e30][ExtensionHostConnection] <2125069> Extension Host Process exited with code: 0, signal: null.
[21:52:08] [127.0.0.1][a2f906dd][ManagementConnection] New connection established.
[21:52:08] [127.0.0.1][7ced2498][ExtensionHostConnection] New connection established.
[21:52:08] [127.0.0.1][7ced2498][ExtensionHostConnection] <2559933> Launched Extension Host Process.
[21:53:25] [127.0.0.1][a2f906dd][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[21:53:25] [127.0.0.1][7ced2498][ExtensionHostConnection] <2559933> Extension Host Process exited with code: 0, signal: null.
[21:53:37] [127.0.0.1][0afa634a][ManagementConnection] New connection established.
[21:53:37] [127.0.0.1][29d8ab86][ExtensionHostConnection] New connection established.
[21:53:37] [127.0.0.1][29d8ab86][ExtensionHostConnection] <2560242> Launched Extension Host Process.
[IPC Library: Pty Host]  INFO Persistent process "21": Replaying 3741 chars and 1 size events
[IPC Library: Pty Host]  INFO Persistent process "22": Replaying 1250 chars and 1 size events
[21:53:45] [127.0.0.1][93687a4a][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[21:53:45] [127.0.0.1][bafcecf3][ExtensionHostConnection] <2558525> Extension Host Process exited with code: 0, signal: null.
[21:54:39] [127.0.0.1][0afa634a][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[21:54:39] Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/server/node/server.main.js:143:7914)
    at process.emit (node:events:390:28)
[21:55:03] [127.0.0.1][0afa634a][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[21:55:03] [127.0.0.1][0afa634a][ManagementConnection] The client has reconnected.
[21:55:03] [127.0.0.1][29d8ab86][ExtensionHostConnection] The client has reconnected.
rejected promise not handled within 1 second: Error: Could not find pty on pty host
stack trace: Error: Could not find pty on pty host,    at m._throwIfNoPty (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:5333),    at m.updateIcon (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:1733),    at Object.call (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:13:8361),    at g.onPromise (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4879),    at g.onRawMessage (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4267),    at /home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:3555,    at D.invoke (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at N.deliver (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:2271),    at h.fire (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:1849),    at process.p (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:6:34973),    at process.emit (node:events:390:28),    at emit (node:internal/child_process:917:12),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[21:55:04] [Error: Could not find pty on pty host,    at m._throwIfNoPty (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:5333),    at m.updateIcon (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:1733),    at Object.call (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:13:8361),    at g.onPromise (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4879),    at g.onRawMessage (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4267),    at /home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:3555,    at D.invoke (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at N.deliver (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:2271),    at h.fire (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:1849),    at process.p (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:6:34973),    at process.emit (node:events:390:28),    at emit (node:internal/child_process:917:12),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: Error: Could not find pty on pty host
stack trace: Error: Could not find pty on pty host,    at m._throwIfNoPty (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:5333),    at m.updateTitle (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:1673),    at Object.call (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:13:8361),    at g.onPromise (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4879),    at g.onRawMessage (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4267),    at /home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:3555,    at D.invoke (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at N.deliver (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:2271),    at h.fire (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:1849),    at process.p (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:6:34973),    at process.emit (node:events:390:28),    at emit (node:internal/child_process:917:12),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[21:55:04] [Error: Could not find pty on pty host,    at m._throwIfNoPty (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:5333),    at m.updateTitle (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:1673),    at Object.call (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:13:8361),    at g.onPromise (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4879),    at g.onRawMessage (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4267),    at /home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:3555,    at D.invoke (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at N.deliver (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:2271),    at h.fire (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:1849),    at process.p (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:6:34973),    at process.emit (node:events:390:28),    at emit (node:internal/child_process:917:12),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: Error: Could not find pty on pty host
stack trace: Error: Could not find pty on pty host,    at m._throwIfNoPty (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:5333),    at m.updateTitle (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:1673),    at Object.call (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:13:8361),    at g.onPromise (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4879),    at g.onRawMessage (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4267),    at /home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:3555,    at D.invoke (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at N.deliver (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:2271),    at h.fire (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:1849),    at process.p (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:6:34973),    at process.emit (node:events:390:28),    at emit (node:internal/child_process:917:12),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[21:55:04] [Error: Could not find pty on pty host,    at m._throwIfNoPty (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:5333),    at m.updateTitle (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:1673),    at Object.call (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:13:8361),    at g.onPromise (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4879),    at g.onRawMessage (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4267),    at /home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:3555,    at D.invoke (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at N.deliver (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:2271),    at h.fire (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:1849),    at process.p (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:6:34973),    at process.emit (node:events:390:28),    at emit (node:internal/child_process:917:12),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
rejected promise not handled within 1 second: Error: Could not find pty on pty host
stack trace: Error: Could not find pty on pty host,    at m._throwIfNoPty (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:5333),    at m.updateTitle (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:1673),    at Object.call (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:13:8361),    at g.onPromise (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4879),    at g.onRawMessage (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4267),    at /home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:3555,    at D.invoke (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at N.deliver (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:2271),    at h.fire (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:1849),    at process.p (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:6:34973),    at process.emit (node:events:390:28),    at emit (node:internal/child_process:917:12),    at processTicksAndRejections (node:internal/process/task_queues:84:21)
[21:55:05] [Error: Could not find pty on pty host,    at m._throwIfNoPty (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:5333),    at m.updateTitle (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:20:1673),    at Object.call (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:13:8361),    at g.onPromise (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4879),    at g.onRawMessage (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:4267),    at /home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:12:3555,    at D.invoke (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:145),    at N.deliver (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:2271),    at h.fire (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:8:1849),    at process.p (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/platform/terminal/node/ptyHostMain.js:6:34973),    at process.emit (node:events:390:28),    at emit (node:internal/child_process:917:12),    at processTicksAndRejections (node:internal/process/task_queues:84:21)]
[23:20:43] [127.0.0.1][bafb3b26][ManagementConnection] New connection established.
[23:20:43] [127.0.0.1][b21e57f4][ExtensionHostConnection] New connection established.
[23:20:43] [127.0.0.1][b21e57f4][ExtensionHostConnection] <1873361> Launched Extension Host Process.
[IPC Library: Pty Host]  INFO Persistent process "21": Replaying 9225 chars and 1 size events
[IPC Library: Pty Host]  INFO Persistent process "22": Replaying 1705 chars and 1 size events
[IPC Library: Pty Host]  INFO Persistent process "39": Replaying 8365 chars and 1 size events
[23:31:36] [127.0.0.1][0afa634a][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[23:31:36] Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/user11/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/server/node/server.main.js:143:7914)
    at process.emit (node:events:390:28)
[00:50:34] [File Watcher (node.js)] Watcher shutdown because watched path got deleted
[02:31:42] [127.0.0.1][0afa634a][ManagementConnection] The reconnection grace time of 3h has expired, so the connection will be disposed.
[02:31:47] [127.0.0.1][29d8ab86][ExtensionHostConnection] <2560242> Extension Host Process exited with code: 0, signal: null.
[11:20:46] Getting Manifest... golang.go
[11:20:47] Installing extension: golang.go
[11:20:47] Downloaded extension: golang.go /home/user11/.vscode-server/data/CachedExtensionVSIXs/golang.go-0.33.1
[11:20:47] Extracted extension to /home/user11/.vscode-server/extensions/.2c0a8f04-c777-4e3a-ac55-6ee10b231a0b: golang.go
[11:20:47] Renamed to /home/user11/.vscode-server/extensions/golang.go-0.33.1
[11:20:47] Extracting completed. golang.go
[11:20:47] Extension installed successfully: golang.go
